In [1]:
import urllib
from bs4 import BeautifulSoup
import requests
import pandas as pd
import lxml
import html5lib
import time

In [2]:
url = "https://www.4sport-live.com/results/home2/?event=3429&lan=H&clean=3&gc=0&page="

In [3]:
new_df = {}
def collect_table (num):
    dfs = []
    dfs = pd.read_html(url + str(num))
    new_df[num] = dfs[0]
    time.sleep(5)
    
pd.Series(range(0,2)).apply(collect_table)

0    None
1    None
dtype: object

In [9]:
pd.concat(new_df.values(), ignore_index=True)

,Unnamed: 0,שם,קטגוריה,תוצאה,זמן אישי,מיקוםכללי,מיקוםקטגוריה,מועדון,הערה
0,NaN,Vincent Kipsang Rono,גברים כללי מרתון,02:12:55,02:12:54,1,1,Kenia,NaN
1,NaN,Alfred Kipkemboi Koech,גברים כללי מרתון,02:15:38,02:15:37,2,2,Kenia,NaN
2,NaN,John Langat,גברים כללי מרתון,02:17:50,02:17:50,3,3,Kenia,NaN
3,NaN,Guadi Agaz,גברים כללי מרתון,02:24:14,02:24:14,4,4,מכבי אתלטי נגב,NaN
4,NaN,Mulushet Zewdu Daniel,גברים כללי מרתון,02:30:25,02:30:24,5,5,Tel Aviv,NaN
5,NaN,פנטה גזאצו,גברים כללי מרתון,02:33:43,02:33:42,6,6,petha tiqwa,NaN
6,NaN,1 קריספל יניב,גברים 44-40 מרתון,02:38:38,02:38:37,7,1,NaN,NaN
7,NaN,Bar Ran,גברים 44-40 מרתון,02:43:22,02:42:49,8,2,runrun,NaN
8,NaN,1 Goryachev Andrey,גברים כללי מרתון,02:45:07,02:45:03,9,7,haifa,NaN
9,NaN,Huja Shimon,גברים כללי מרתון,02:45:15,02:45:13,10,8,M&M,NaN
10,NaN,Fein Amit,גברים כללי מרתון,02:47:28,02:47:26,11,9,אנשים בספורט,NaN
11,NaN,accos ronen,גברים 59-55 מרתון,02:48:11,02:48:09,12,1,M&M,NaN
12,NaN,Ribeiro Ricardo,גברים כללי מרתון,02:49:19,02:49:08,13,10,POR,NaN
13,NaN,ליאון שלומי,גברים 49-45 מרתון,02:50:05,02:50:04,14,1,התעשייה האוירית,NaN
14,NaN,GREEN ERAAN,גברים 49-45 מרתון,02:50:23,02:50:19,15,2,"עיריית ת""א",NaN
15,NaN,Ben gedaliya Omer,גברים כללי מרתון,02:50:47,02:50:45,16,11,Talmon,NaN
16,NaN,מובשוביץ תמיר,גברים כללי מרתון,02:51:31,02:51:29,17,12,אחים לחיים,NaN
17,NaN,Dahan Ron,גברים כללי מרתון,02:51:52,02:51:49,19,13,חבר,NaN
18,NaN,Terem Eyal,גברים 44-40 מרתון,02:51:56,02:51:49,18,3,מישהו לרוץ איתו,NaN
19,NaN,ביקאיה מינטמר,נשים כללי מרתון,02:53:01,02:53:00,1,1,רצי הסימטה,NaN
20,NaN,Vincent Kipsang Rono,גברים כללי מרתון,02:12:55,02:12:54,1,1,Kenia,NaN
21,NaN,Alfred Kipkemboi Koech,גברים כללי מרתון,02:15:38,02:15:37,2,2,Kenia,NaN
22,NaN,John Langat,גברים כללי מרתון,02:17:50,02:17:50,3,3,Kenia,NaN
23,NaN,Guadi Agaz,גברים כללי מרתון,02:24:14,02:24:14,4,4,מכבי אתלטי נגב,NaN
24,NaN,Mulushet Zewdu Daniel,גברים כללי מרתון,02:30:25,02:30:24,5,5,Tel Aviv,NaN
25,NaN,פנטה גזאצו,גברים כללי מרתון,02:33:43,02:33:42,6,6,petha tiqwa,NaN
26,NaN,1 קריספל יניב,גברים 44-40 מרתון,02:38:38,02:38:37,7,1,NaN,NaN
27,NaN,Bar Ran,גברים 44-40 מרתון,02:43:22,02:42:49,8,2,runrun,NaN
28,NaN,1 Goryachev Andrey,גברים כללי מרתון,02:45:07,02:45:03,9,7,haifa,NaN
29,NaN,Huja Shimon,גברים כללי מרתון,02:45:15,02:45:13,10,8,M&M,NaN
30,NaN,Fein Amit,גברים כללי מרתון,02:47:28,02:47:26,11,9,אנשים בספורט,NaN
31,NaN,accos ronen,גברים 59-55 מרתון,02:48:11,02:48:09,12,1,M&M,NaN
32,NaN,Ribeiro Ricardo,גברים כללי מרתון,02:49:19,02:49:08,13,10,POR,NaN
33,NaN,ליאון שלומי,גברים 49-45 מרתון,02:50:05,02:50:04,14,1,התעשייה האוירית,NaN
34,NaN,GREEN ERAAN,גברים 49-45 מרתון,02:50:23,02:50:19,15,2,"עיריית ת""א",NaN
35,NaN,Ben gedaliya Omer,גברים כללי מרתון,02:50:47,02:50:45,16,11,Talmon,NaN
36,NaN,מובשוביץ תמיר,גברים כללי מרתון,02:51:31,02:51:29,17,12,אחים לחיים,NaN
37,NaN,Dahan Ron,גברים כללי מרתון,02:51:52,02:51:49,19,13,חבר,NaN
38,NaN,Terem Eyal,גברים 44-40 מרתון,02:51:56,02:51:49,18,3,מישהו לרוץ איתו,NaN
39,NaN,ביקאיה מינטמר,נשים כללי מרתון,02:53:01,02:53:00,1,1,רצי הסימטה,NaN

In [4]:
dat.to_csv('runner.csv',  encoding='utf-8')

print("script complete")

NameError: name 'dat' is not defined

In [4]:
new_df = []
pd.Series(range(0,2)).apply(collect_table)
# collect_table(1)
new_df

[    Unnamed: 0                      שם            קטגוריה     תוצאה  זמן אישי  \
 0          NaN    Vincent Kipsang Rono   גברים כללי מרתון  02:12:55  02:12:54
 1          NaN  Alfred Kipkemboi Koech   גברים כללי מרתון  02:15:38  02:15:37
 2          NaN             John Langat   גברים כללי מרתון  02:17:50  02:17:50
 3          NaN              Guadi Agaz   גברים כללי מרתון  02:24:14  02:24:14
 4          NaN   Mulushet Zewdu Daniel   גברים כללי מרתון  02:30:25  02:30:24
 5          NaN              פנטה גזאצו   גברים כללי מרתון  02:33:43  02:33:42
 6          NaN          1  קריספל יניב  גברים 44-40 מרתון  02:38:38  02:38:37
 7          NaN                 Bar Ran  גברים 44-40 מרתון  02:43:22  02:42:49
 8          NaN     1  Goryachev Andrey   גברים כללי מרתון  02:45:07  02:45:03
 9          NaN             Huja Shimon   גברים כללי מרתון  02:45:15  02:45:13
 10         NaN               Fein Amit   גברים כללי מרתון  02:47:28  02:47:26
 11         NaN             accos ronen  גברים 59-55 מרתון  02:48:11  02:48:09
 12         NaN         Ribeiro Ricardo   גברים כללי מרתון  02:49:19  02:49:08
 13         NaN             ליאון שלומי  גברים 49-45 מרתון  02:50:05  02:50:04
 14         NaN             GREEN ERAAN  גברים 49-45 מרתון  02:50:23  02:50:19
 15         NaN       Ben gedaliya Omer   גברים כללי מרתון  02:50:47  02:50:45
 16         NaN           מובשוביץ תמיר   גברים כללי מרתון  02:51:31  02:51:29
 17         NaN               Dahan Ron   גברים כללי מרתון  02:51:52  02:51:49
 18         NaN              Terem Eyal  גברים 44-40 מרתון  02:51:56  02:51:49
 19         NaN           ביקאיה מינטמר    נשים כללי מרתון  02:53:01  02:53:00

     מיקוםכללי  מיקוםקטגוריה           מועדון  הערה
 0           1             1            Kenia   NaN
 1           2             2            Kenia   NaN
 2           3             3            Kenia   NaN
 3           4             4   מכבי אתלטי נגב   NaN
 4           5             5         Tel Aviv   NaN
 5           6             6      petha tiqwa   NaN
 6           7             1              NaN   NaN
 7           8             2           runrun   NaN
 8           9             7            haifa   NaN
 9          10             8              M&M   NaN
 10         11             9     אנשים בספורט   NaN
 11         12             1              M&M   NaN
 12         13            10              POR   NaN
 13         14             1  התעשייה האוירית   NaN
 14         15             2       עיריית ת"א   NaN
 15         16            11           Talmon   NaN
 16         17            12       אחים לחיים   NaN
 17         19            13              חבר   NaN
 18         18             3  מישהו לרוץ איתו   NaN
 19          1             1       רצי הסימטה   NaN  ,
     Unnamed: 0                      שם            קטגוריה     תוצאה  זמן אישי  \
 0          NaN    Vincent Kipsang Rono   גברים כללי מרתון  02:12:55  02:12:54
 1          NaN  Alfred Kipkemboi Koech   גברים כללי מרתון  02:15:38  02:15:37
 2          NaN             John Langat   גברים כללי מרתון  02:17:50  02:17:50
 3          NaN              Guadi Agaz   גברים כללי מרתון  02:24:14  02:24:14
 4          NaN   Mulushet Zewdu Daniel   גברים כללי מרתון  02:30:25  02:30:24
 5          NaN              פנטה גזאצו   גברים כללי מרתון  02:33:43  02:33:42
 6          NaN          1  קריספל יניב  גברים 44-40 מרתון  02:38:38  02:38:37
 7          NaN                 Bar Ran  גברים 44-40 מרתון  02:43:22  02:42:49
 8          NaN     1  Goryachev Andrey   גברים כללי מרתון  02:45:07  02:45:03
 9          NaN             Huja Shimon   גברים כללי מרתון  02:45:15  02:45:13
 10         NaN               Fein Amit   גברים כללי מרתון  02:47:28  02:47:26
 11         NaN             accos ronen  גברים 59-55 מרתון  02:48:11  02:48:09
 12         NaN         Ribeiro Ricardo   גברים כללי מרתון  02:49:19  02:49:08
 13         NaN             ליאון שלומי  גברים 49-45 מרתון  02:50:05  02:50:04
 14         NaN             GREEN ERAAN  גברים 49-45 מרתון  02:50:23  02:50:19
 15         NaN       Ben gedaliya Omer   גברים כללי מרתון  02:50:47  02:50:45
 16         NaN           מובשוביץ תמיר   גברים כללי מרתון  02:51:31  02:51:29
 17         NaN               Dahan Ron   גברים כללי מרתון  02:51:52  02:51:49
 18         NaN              Terem Eyal  גברים 44-40 מרתון  02:51:56  02:51:49
 19         NaN           ביקאיה מינטמר    נשים כללי מרתון  02:53:01  02:53:00

     מיקוםכללי  מיקוםקטגוריה           מועדון  הערה
 0           1             1            Kenia   NaN
 1           2             2            Kenia   NaN
 2           3             3            Kenia   NaN
 3           4             4   מכבי אתלטי נגב   NaN
 4           5             5         Tel Aviv   NaN
 5           6             6      petha tiqwa   NaN
 6           7             1              NaN   NaN
 7           8             2           runrun   NaN
 8           9             7            haifa   NaN
 9          10             8              M&M   NaN
 10         11             9     אנשים בספורט   NaN
 11         12             1              M&M   NaN
 12         13            10              POR   NaN
 13         14             1  התעשייה האוירית   NaN
 14         15             2       עיריית ת"א   NaN
 15         16            11           Talmon   NaN
 16         17            12       אחים לחיים   NaN
 17         19            13              חבר   NaN
 18         18             3  מישהו לרוץ איתו   NaN
 19          1             1       רצי הסימטה   NaN  ]

In [35]:
dat = pd.concat(new_df)

In [36]:
dat = dat.iloc[:, 1:]
dat.columns = ["name", "category", "score", "personal_time", "rank", "rank_category", "club", "notes"]


dat[['gender','run_category', 'age_group']] = dat['category'].str.split(" ", expand = True)
# dat

In [37]:
dat.head()

,name,category,score,personal_time,rank,rank_category,club,notes,gender,run_category,age_group
0,Vincent Kipsang Rono,גברים כללי מרתון,02:12:55,02:12:54,1,1,Kenia,NaN,גברים,כללי,מרתון
1,Alfred Kipkemboi Koech,גברים כללי מרתון,02:15:38,02:15:37,2,2,Kenia,NaN,גברים,כללי,מרתון
2,John Langat,גברים כללי מרתון,02:17:50,02:17:50,3,3,Kenia,NaN,גברים,כללי,מרתון
3,Guadi Agaz,גברים כללי מרתון,02:24:14,02:24:14,4,4,מכבי אתלטי נגב,NaN,גברים,כללי,מרתון
4,Mulushet Zewdu Daniel,גברים כללי מרתון,02:30:25,02:30:24,5,5,Tel Aviv,NaN,גברים,כללי,מרתון

In [56]:
dat['personal_time'] = pd.to_timedelta(dat['personal_time'], unit = 'm')
dat['score'] = pd.to_timedelta(dat['score'], unit = 'm')

In [25]:
collect_table(652)